name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.9"] # ${{ needs.prepare.outputs.python-version-list }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install PyQt6
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: unit test
      run: |
        python -m unittest tests/main_tab_tests.py
    - name: Send failure mesage
      if: failure()
      uses: an3park/telegram-action@v1
      with:
        bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
        message: 'Build failed!'